version: '3'

services:
   mysql:
     image: mysql:5.7
     container_name: mysql
     volumes:
       - /data/mysql/log:/var/log/mysql
       - /data/mysql/data:/var/lib/mysql
       - /data/mysql/conf.d:/etc/mysql/conf.d
       - /etc/localtime:/etc/localtime:ro
     ports:
       - 3306:3306
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root